language: node_js
node_js:
- '6'
before_script:
- gem install net-ssh -v 2.9.2
- gem install rhc
- npm install grunt-cli -g
- ssh-keyscan -H -t rsa,dsa $OPENSHIFT_DOMAIN >> ~/.ssh/known_hosts
- echo -e $OPENSHIFT_KEY > ~/.ssh/id_rsa
- chmod 400 ~/.ssh/id_rsa
script:
- grunt
- export OPENSHIFT_SSH=`rhc app show -l $OPENSHIFT_USER -p $OPENSHIFT_PASS $OPENSHIFT_APP|grep SSH:|cut -c10-|tr -d  ' '`
- echo "$OPENSHIFT_SSH"
- ssh $OPENSHIFT_SSH "sh -e 'rm -rf app-root/repo/www/mobilete;mkdir -p app-root/repo/www/mobilete'"
- scp -r output/www  "$OPENSHIFT_SSH":app-root/repo/www/mobilete