language: node_js
node_js:
- '6'
before_script:
- npm install grunt-cli -g
- ssh-keyscan -H -t rsa,dsa $OPENSHIFT_DOMAIN >> ~/.ssh/known_hosts
- echo -e $OPENSHIFT_KEY > ~/.ssh/id_rsa
- chmod 400 ~/.ssh/id_rsa
script:
- grunt
- export BRANCH_NAME=`[[ $TRAVIS_BRANCH = "master" ]] && a="" || a="_$TRAVIS_BRANCH";echo $a`
- export SRC_DIR=`[[ $TRAVIS_BRANCH = "master" ]] && a="output/www" || a="www";echo $a`
- echo "$SRC_DIR $BRANCH_NAME"
- ssh $OPENSHIFT_SSH rm -rf app-root/repo/www/mobilete$BRANCH_NAME
- scp -r $SRC_DIR  "$OPENSHIFT_SSH":app-root/repo/www/mobilete$BRANCH_NAME