language: node_js
node_js:
- '6'
before_script:
- npm install grunt-cli -g
- ssh-keyscan -H -t rsa,dsa $OPENSHIFT_DOMAIN >> ~/.ssh/known_hosts
- echo -e $OPENSHIFT_KEY > ~/.ssh/id_rsa
- chmod 400 ~/.ssh/id_rsa
script:
- grunt
- export BRANCH_NAME=`echo "$TRAVIS_BRANCH"|grep -v master`
- echo "$OPENSHIFT_SSH $BRANCH_NAME"
- ssh $OPENSHIFT_SSH rm -rf app-root/repo/www/mobilete$BRANCH_NAME
- scp -r output/www  "$OPENSHIFT_SSH":app-root/repo/www/mobilete$BRANCH_NAME