language: node_js
node_js:
- '6'
before_script:
- gem install net-ssh -v 2.9.2
- gem install rhc
- npm install grunt-cli -g
- ssh-keyscan -H -t rsa,dsa $OPENSHIFT_DOMAIN >> ~/.ssh/known_hosts
- echo "OPENSHIFT__KEY" > ~/.ssh/id_rsa
script:
- grunt
- rhc ssh -l $OPENSHIFT_USER -p $OPENSHIFT_PASS $OPENSHIFT_APP -- "rm -rf app-root/repo/www/mobilete"
- rhc scp -l $OPENSHIFT_USER -p $OPENSHIFT_PASS $OPENSHIFT_APP upload output/www app-root/repo/www/mobilete